### ISSUE TITLE
Calculation for rack of record counts

### ISSUE THREAD

**Issue by shawjordan** [AquaqProdSupport1/TorQ-Finance-Starter-Pack#12]
Hey Support!

I need a function that calculates a rack of record counts, grouped by a list of fields, for all tables in the RTD, within a certain timeframe.

The fields for grouping should be supplied as a list.

The function should have a signature like:

f[st;et;list];

Thanks,
Brittany B Brandi

**Comment by bmcguckin** [comment]
Hi Brittanny, 

Here is the Query you were looking for. Apologies for the delay. 

`// FUCNTION 
f:{[st;et;list] 
    tabs: tables[] where {[list;t] $[min list in cols t;1b;0b]}[list]'[tables[]]; 
    groupby:{[fields] $[-11h=type fields; (enlist fields)!enlist fields; (fields)!fields]};
    cnt: enlist(#:;`i);
    rackcount:{[st;et;list;t]?[t;enlist (within;`time;(enlist;st;et));
                groupby[list];(enlist t)!cnt]}[st;et;list]'[tabs];
    list xkey (where 0=sum each 1_ flip 0!a)_0!a:{x uj y}/[();rackcount]
    
}
//EXAMPLE RESULT
f[09:00;09:10;`sym`ex]
sym  ex| clienttrade quote srcquote trade
-------| --------------------------------
AAPL N | 694         3341  3240     719
AIG  O | 732         3205  3339     728
AMD  N | 751         3276  3209     739
DELL N | 742         3346  3354     713
DOW  O | 755         3268  3373     723
GOOG N | 727         3297  3318     647
HPQ  O | 755         3211  3304     750
IBM  N | 742         3374  3313     721
INTC N | 686         3427  3365     701
MSFT N | 727         3319  3494     747
//NOTE - Function removes the empty columns`


Regards, 
Prod Support 1

**Comment by ThomasSmyth** [comment]
The conditional is redundant here: `$[min list in cols t;1b;0b]`.
For `groupby` you can avoid checking types by forcing atoms to be lists with `()`: `{x!x}(),fields`
Avoid using primitives like `#:` instead of `count` (I'm sure this came up in the parse tree).
`uj/[rackcount]` should work without the lambda too.

**Comment by bmcguckin** [comment]
@ThomasSmyth Thank you for your comment. Will be posting the updated query shortly, testing that the new version works correctly.

**Comment by jonathonmcmurray** [comment]
I think you can get rid of the first lambda with some adverbs, something like

`tables[] where min each list in/:cols each tables[]`

But check which is faster

**Comment by bmcguckin** [comment]
UPDATE. Speed check with changing tabs definition to have adverbs. 
With adverbs below:
```
g:{[st;et;list]tabs:tables[] where min each list in/:cols each tables[];groupby:{[fields]{x!x}(),fields};rackcount:{[st;et;list;func;t]?[t;enlist[(within;`time;enlist[st;et])];func[list];enlist[t]!enlist[(count;`i)]]}[st;et;list;groupby]'[tabs];list xkey (where 0=sum each 1_ flip 0!a)_0!a:uj/[rackcount]}
```
Speed check of adverb definition: implies an average time of 6130.333milliseconds 
```
\t:10 g[08:10;08:15;`sym]
6170
\t:10 g[08:10;08:15;`sym]
6168
\t:10 g[08:10;08:15;`sym]
6053
```
Speed check of previous lambda version: implies an average time of 6183.333milliseconds
```
\t:10 g[08:10;08:15;`sym]
6107
\t:10 g[08:10;08:15;`sym]
6524
\t:10 g[08:10;08:15;`sym]
5919
```
So there is a fractional improvement using an adverb definition instead of the first lambda version.
